
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 29 18:08:32 BRT 2023
//----------------------------------------------------

package SyntaxAnalyzer;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FUNCTION_NAME = 13;
  public static final int ABRE_P = 14;
  public static final int PROGRAMA = 2;
  public static final int CONST_NUMBER = 10;
  public static final int CONST_CHAR = 9;
  public static final int TIPO_INTEIRO = 5;
  public static final int INICIO = 3;
  public static final int PTVG = 7;
  public static final int EOF = 0;
  public static final int FIM = 4;
  public static final int TIPO_CHAR = 6;
  public static final int KEYWORDS = 12;
  public static final int VARIABLE_NAME = 11;
  public static final int VGL = 16;
  public static final int error = 1;
  public static final int SIMBOLO_ATRIB = 8;
  public static final int FECHA_P = 15;
}

